- .gitignore
> Meta: Add Webstorm directories to .gitignore

- src/commands/quickLinksCommand.ts
(And also specify the array type explicity)
> QuickLinks: Add a link to wsl build notes

- package.json
- src/apis/githubAPI.ts
- src/commandHandler.ts
- src/commands/index.ts
- src/commands/issueCommand.ts
- src/commands/prCommand.ts
- src/commands/quickLinksCommand.ts
- src/config/secrets.ts
- src/models/commandParser.ts
- yarn.lock
This also renames the discord token environment variable to "discord_token" and adds an optional github token environment variable ("github_token") that allows the bot to have a higher rate limit by linking it against a github account. (https://octokit.github.io/rest.js/v18#authentication)
> Commands: Add Github related commands

- src/commands/quickLinksCommand.ts
This helps reduce chat clutter as well as make the respones look more seamless :^)
> CommandHandler: Delete command message after it is processed

- src/apis/githubAPI.ts
- src/commands/issueCommand.ts
- src/commands/prCommand.ts
- src/models/commandParser.ts
Also uses the actual emote for `:^)`
> IssueCommand/PrCommand: Use embeds; allow querying by issue/PR number

- src/commands/quickLinksCommand.ts
> Add !soytineres command

- .eslintrc
- src/apis/githubAPI.ts
- src/commands/issueCommand.ts
- src/commands/manCommand.ts
- src/commands/prCommand.ts
- src/index.ts
This introduces a new linting rule enforcing camelCase in all files and applies those rules.
Resolves #22
> CI+Everywhere: Enforce consistent identifier formatting

- src/commands/issueCommand.ts
- src/commands/prCommand.ts
This adds the "Labels" field for both pull requests and issues as well as the "Closed" field for issues (similar to "Merged" for prs)
> PrCommand+IssueCommand: Add more fields to embeds

- src/commands/test262Command.ts
- src/util/emoji.ts
This replaces the previous status icons with a set of emojis
chosen and partly created by members of the discord server :^)
> Commands: Update test262 status icons

- src/commands/test262Command.ts
Commands: Fix output of "!test262 labels"
This replaces the previous map of labels to an icon string or a supplier
function with function returning the icon for a given label.
Instead of iterating over the map to obtain all labels,
the "!test262 labels" command now uses the labels present in the first
result
> Commands: Fix output of "!test262 labels"

- src/commands/manCommand.ts
Add support for "!man page(section)" in addition to the already existing "!man section page"﻿
> Commands: Support "page(section)" format in man command

- src/commands/emojiCommand.ts
Continuation of #85 as requested changes weren't implemented yet
> Commands: Use embed for emoji command instead of sending emoji directly

- README.md
- src/config/secrets.ts
Two small tweaks that helped me getting started.
> Small docs tweaks

- package.json
- src/apis/githubAPI.ts
- src/commandHandler.ts
- src/commands/index.ts
- src/commands/quoteCommand.ts
- src/config/secrets.ts
- src/index.ts
- src/models/commandParser.ts
- yarn.lock
This command can be used by 100 commit club members to create a pull request based on a discord message they deem quote worthy.
> Commands: Add the QuoteCommand

- src/commands/quoteCommand.ts
CC: @alimpfard mentioned this on the discord.
> Commands: Use guild nickname for quote attribution and command issuer

- .github/workflows/ci.yml
- package.json
- src/commands/emojiCommand.ts
- src/commands/githubCommand.ts
- src/commands/manCommand.ts
- src/commands/planCommand.ts
- src/commands/quoteCommand.ts
- src/commands/test262Command.ts
- src/index.ts
- src/models/commandParser.ts
- yarn.lock
NOTE: I'm not sure what controls the Node version installed on Heroku, which might need a change.
> Update discord.js to v13

- src/commandHandler.ts
- src/commands/command.ts
- src/commands/emojiCommand.ts
- src/commands/githubCommand.ts
- src/commands/manCommand.ts
- src/commands/planCommand.ts
- src/commands/quickLinksCommand.ts
- src/commands/quoteCommand.ts
- src/commands/test262Command.ts
- src/index.ts
This pull request fixes various issues, adds new features and improves existing features.
Highlights include:
- Running /quote on a message directly from the context menu
- Using discords fancy timestamp formatting for /github
> Commands: Various improvements

- .github/workflows/ci.yml
> CI: Test full development and production matrix

- src/commandHandler.ts
> CommandHandler: Fix TypeError in debug mode logging command interaction

- src/commands/githubCommand.ts
Adds a url option to allow using a full url too
> GithubCommand: Add url option

- src/apis/githubAPI.ts
- src/commandHandler.ts
- src/commands/command.ts
- src/commands/index.ts
- src/commands/userCommand.ts
- src/index.ts
- src/util/embedFromIssueOrPull.ts
- src/util/emoji.ts
Demo:
https://streamable.com/faydji
> User: Add User command

- src/commands/test262Command.ts
- src/util/emoji.ts
> Commands: Show :makemore: for test262 whenever tests get added :^)

- src/commands/githubCommand.ts
- src/commands/manCommand.ts
- src/commands/test262Command.ts
- src/util/embedFromIssueOrPull.ts
This pull request does minor cleanups by removing duplicated code and updating deprecated function calls
> Everywhere: Some housekeeping

- src/commands/quickLinksCommand.ts
As suggested by kleines Filmröllchen here: https://discord.com/channels/830522505605283862/830522505605283866/972937603374514297
> QuickLinksCommand: Add /whf

- src/commands/quickLinksCommand.ts
As suggested by Agni here: https://discordapp.com/channels/830522505605283862/830739873119207426/973186557932601384
> QuickLinksCommand: Add /emacs

- src/index.ts
The embed suppression feature currently doesn't work in the production environment. This pull request adds debug logging for the event handler to hopefully figure out what the problem is
> Index: Fix deprecation warning and add debug logging

- .gitignore
- src/apis/githubAPI.ts
- src/commandHandler.ts
- src/commands/commitStatsCommand.ts
- src/commands/index.ts
- src/commands/userCommand.ts
- src/config/botConfig.ts
- src/util/text.ts
- tests/githubAPI.test.ts
Introducing `/commit-stats`
Oh wow, this command can be yours for just as little as $0, yes, the offer is even valid in Nebraska!
Now ain't that a damn good deal!!
> Commands: Add a brand spanking new `commit-stats` command

- src/apis/githubAPI.ts
> API+ManCommand: Fix manpage encoding mismatch (#430)

- src/commands/commitStatsCommand.ts
- src/commands/userCommand.ts
- src/util/color.ts
- src/util/embedFromIssueOrPull.ts
- src/util/emoji.ts
- src/util/text.ts
> CommitStatsCommand: Redesign

- package.json
- src/commandHandler.ts
- src/commands/command.ts
- src/commands/commitStatsCommand.ts
- src/commands/emojiCommand.ts
- src/commands/githubCommand.ts
- src/commands/index.ts
- src/commands/manCommand.ts
- src/commands/planCommand.ts
- src/commands/quickLinksCommand.ts
- src/commands/quoteCommand.ts
- src/commands/test262Command.ts
- src/commands/userCommand.ts
- src/index.ts
- src/util/embedFromIssueOrPull.ts
- yarn.lock
Additionally, every command now
- uses the `SlashCommandBuilder` instead of directly providing JSON.
- have their handlers properly typed.
Some parts of this commit are based on @bgianfo's work in #647.
> Deps+Everywhere: Upgrade `discord.js` to `v14`

- package.json
- src/util/embedFromIssueOrPull.ts
- yarn.lock
This required some manual action due to changes in the typings.
> Deps: Upgrade @octokit/rest

- src/commands/manCommand.ts
I was browsing through all the functions of BuggieBot, and noticed that one of them was not quite right, so I had to fix it ^^
> ManCommand: Fix description

- package.json
- src/config/secrets.ts
- src/index.ts
- src/mastodon.ts
- tsconfig.json
- typings/mastodon.d.ts
- yarn.lock
This pull request adds support for announcing announcement messages from a channel on mastodon
(announcement_mastodon_token has been added to the bot's environment)
> Announce announcements on Mastodon
