SerenityOS/discord-bot

- src/commandHandler.ts
The help command has to be implemented in the command handler, as it holds the list of available commands
(This PR also includes a small commit that adds a missing await)
> CommandHandler: Implement simple help command 

- src/commands/issueCommand.ts
- src/commands/prCommand.ts
This fixes the issue of discord not preprocessing bots' messages for any custom emoji strings (ala :sadcaret:) and replacing them with the ID format. This commit uses the ID format explicitly to fix that.
In the future it might be beneficial to use the discordjs api somehow to not hardcode the emoji ID.
> IssueCommand+PRCommand: Use emoji ID to correctly display custom emoji

- src/models/commandParser.ts
Sometimes it is useful to ping someone while running a command, i.e.
!pr <pr number> @user
However, currently the bot includes the mention in the search, causing
some annoyance.  This patch removes anything between <> that's a single
word, which both emotes and mentions are.
This could probably be refined further by looking into the mentions
object within the message, but this shouldn't cause any false positives
during normal usage.
> CommandParser: Remove mentions and emotes from commands

- src/models/commandParser.ts
Now it only strips out using discord.js' own RegExp for user mentions.
> MessageParser: Strip user mentions more robustly

- src/commands/issueCommand.ts
- src/commands/manCommand.ts
- src/commands/prCommand.ts
- src/util/emoji.ts
Based off of #11 
> In the future it might be beneficial to use the discordjs api somehow to not hardcode the emoji ID.
This pr creates a new function `getEmoji` which fetches the guild (server) in which a message was received for a custom emoji.
The feature is then used by the `issueCommand` and `prCommand` for the `:sadcaret:` emoji.
> Utils: Add dynamic fetching of guild emojis

- src/commands/prCommand.ts
Previously even a merged pull request would be colored red
This adds a new field containing when the pull request got merged and who merged it
> PrCommand: Minor improvements to the formatting of merged pull requests

- src/apis/githubAPI.ts
- src/commands/manCommand.ts
- src/index.ts
- src/util/emoji.ts
- Send an Embed instead of a markdown codeblock for a man page
- Add emojis to be able to toggle between a collapsed and an extended view
Collapsed:
Expanded:
> ManCommand: Implement embed based format

- src/commands/issueCommand.ts
- src/commands/manCommand.ts
- src/commands/prCommand.ts
- src/config/secrets.ts
- src/index.ts
- src/util/emoji.ts
Previously the emoji cache wouldn't work in private message channels
due to it using a message's guild to resolve an emoji.
As Buggie is currently the only instance of the bot and as said
instance is only being used on the Serenity server there is no
problem in taking a guild as a config variable.
The emoji cache now also not only caches the emoji's name but the whole
reference object.
Resolves #21
> Util+Commands: Cache emojis based on a globally configured guild

- src/commandHandler.ts
- src/commands/index.ts
- src/commands/planCommand.ts
Example usage :
User: `!plan hardware acceleration`
Bot :
```
> Will SerenityOS support hardware acceleration?
Maybe. Maybe not. There is no plan.
(source: <https://github.com/SerenityOS/serenity/blob/master/Documentation/FAQ.md>)
```
Also works without arguments to use the original "Will SerenityOS support `$THING`?" question.
> Add !plan to check if a feature is part of the SerenityOS plan

- src/commands/planCommand.ts
Turns out that the first argument isn't the command name. Which is obvious in retrospect, but somehow not that obvious when writing code!
> PlanCommand: Fix parsing of the first argument

- package.json
- src/apis/githubAPI.ts
- src/commandHandler.ts
- src/commands/index.ts
- src/commands/test262Command.ts
- yarn.lock
This command fetches and outputs the results of the ecma262 tests
run in LibJS from https://libjs.dev/test262.
If no argument is given, the latest commit will be used. Otherwise
the first argument will be used to resolve a commit by hash.
If the first argument is "labels", an overview over the icons
used in the result output will be displayed.
> Commands: Added the test262 command

- src/commands/test262Command.ts
- src/util/emoji.ts
This moves the percentage value of passed tests from the title
of a test's embed field to the first entry in the body.
Additionally, a percentage difference to the previous commit is now shown :^)
> Commands: Inline passing percentage of test262 test with other values

- src/commands/test262Command.ts
It might be a little discouraging to see a change do so little to the percentage that it doesn't even
show so this patch removes such differences.
> Commands: Avoid "[+-]0.00" as difference for test262 passing percentage

- src/commandHandler.ts
- src/commands/emojiCommand.ts
- src/commands/index.ts
- src/util/emoji.ts
This command allows non nitro users to send animated emojis (or any emoji)
from the configured guild into the current chat
> Commands: Add emoji command

- src/commands/test262Command.ts
Instead of just printing the latest test run, an error will now be
shown if a commit could not be found in the results
This was requested by Ali on Discord
> Commands: Print error if commit hash could not be found for !test262

- src/apis/githubAPI.ts
- src/commands/test262Command.ts
I always wished it would show the commit author so it doesn't look like it's my work when invoking the `!test262` command. Now it does :^)
> Add author to test262 embed

- src/commands/issueCommand.ts
- src/commands/prCommand.ts
This prevents a github api error being thrown for using more than
256 characters in a command with the following pattern:
`!pr <number> <message about the pr...>`
`!issue <number> <message about the issue...>`
> Commands: Search for pull requests and issues by first argument if number

- src/commands/test262Command.ts
This should be a bit nicer than a normal test262 response with the title set to "undefined".
> Commands: Print an error if the test262 commit could not be fetched

- src/commands/test262Command.ts
This patch adds support for test result fields that haven't existed
in the previous test or have existed in the previous test but not the
current anymore
> Commands: Properly display when test262 results get added or removed

- src/commands/planCommand.ts
This is kind of a meme on Discord where "wen" is commonly used when
asking for features. As this is the purpose of the "plan" command, an
alias "wen" could make the use of "plan" much funnier.
> Commands: Add "wen" alias for "plan"

- src/commands/githubCommand.ts
This patch replaces the previously used .url (`https://api.github.com/users/<username>`) with .html_url (`https://github.com/<username>`).
> GithubCommand: Use correct profile link for merged_by or closed_by user

- src/apis/githubAPI.ts
The command user's nickname might not match the github username or
be incompatible with github usernames alltogether.
> QuoteCommand: Don't mention users on github

- src/apis/githubAPI.ts
Because the quote command was encoding the fortunes.json file as
binary when it received it from the API it was mangling the utf-8
characters in the file when it it wrote it back when creating the
pull request.
Fix this by always using utf-8 encoding.
> Commands: Fix text encoding of the /quote command

- package.json
- src/commands/test262Command.ts
- yarn.lock
Reverts SerenityOS/discord-bot#212 
This is breaking the `test262` command with the following error: 
```
2021-09-04T18:20:54.915930+00:00 app[worker.1]: Error [ERR_REQUIRE_ESM]: require() of ES Module /app/node_modules/node-fetch/src/index.js from /app/build/commands/test262Command.js not supported.
2021-09-04T18:20:54.915933+00:00 app[worker.1]: Instead change the require of index.js in /app/build/commands/test262Command.js to a dynamic import() which is available in all CommonJS modules.
2021-09-04T18:20:54.915933+00:00 app[worker.1]:     at Object.<anonymous> (/app/build/commands/test262Command.js:13:38)
2021-09-04T18:20:54.915934+00:00 app[worker.1]:     at Object.<anonymous> (/app/build/commands/index.js:35:14)
2021-09-04T18:20:54.915934+00:00 app[worker.1]:     at …
```
> Revert "Dependencies: Bump node-fetch from 2.6.1 to 3.0.0"

- src/commands/githubCommand.ts
This pull request improves the appearance of issue and pull request embeds.
Both types of embeds now show their number in the title, a new state field has been added and draft pull requests will only show the draft color when not closed or merged.
Current:
This branch:
> GithubCommand: Various improvements to embed formatting

- src/commands/githubCommand.ts
This ensures that the url always matches the regex regardless of whats before or after the important part
> GithubCommand: Correct regex parsing issue

- src/commands/test262Command.ts
When a commit has an author with no associated GitHub account, commit.author will be null. However, commit.commit.author will at least give you the author name assigned to the commit. We can't get an avatar URL or profile URL from this though, so the command will just display the author name in this case.
The first response shows the current state of master, the last two responses show two examples with this fix applied.
Fixes #379
> test262Command: Get author name from commit.author if author is null

- src/commands/githubCommand.ts
I hate regex. The + in .+ actually means make sure this takes a character even if it takes it from something else, and the /g doesn't work because :shrug:
> GithubCommand: Fix regex

- src/commands/test262Command.ts
- src/util/emoji.ts
test262Command: Use :yak: emoji instead of the Unicode bison emoji
Andreas added this emoji to the server so that we can have a
consistent yak emoji across all platforms, so lets use it for the
test262 command as well :^).
-----
test262Command: Say "percentage_passing" if the test262 emoji is missing
Previously it would say "undefined".
-----
test262Command: Show test duration differences
> test262Command: Assortment of improvements

- src/commands/manCommand.ts
This pull request makes use of man.serenityos.org as the default title link and adds an explicit link to GitHub as well as serenityos.org to the embed description.
> ManCommand: Add man.serenityos.org as an option for navigation

- src/apis/githubAPI.ts
- src/commands/githubCommand.ts
- src/commands/quoteCommand.ts
- src/util/embedFromIssueOrPull.ts
- tests/githubAPI.test.ts
This pull request adds a new option to the github commands, allowing users to specify which repository they want to query.
Currently `serenity` and `jakt` are supported.
The repository gets inferred automatically based on the channel category the command got run in
> GithubCommand: Allow specifiying a different repository 

- src/index.ts
Repository embeds from discord fill up a lot of screen space without providing much relevant information.
This pull request adds a message listener that removes the embeds on a message automatically if the message has an embed from `github.com` with `blob` or `tree` being the third segment in the pathname (the type of github url). Sadly the api does not allow more fine grain removal of a single embed, however multiple embeds in a single message are quite rare.
As requested by linusg on discord: https://discord.com/channels/830522505605283862/830739873119207426/986007342443282493
> Index: Remove embeds from github.com

- src/index.ts
In some cases the embed of a message wouldn't be cached in the embeds array without fetching the message first.
> Index: Fetch message before checking its embeds

- src/apis/githubAPI.ts
- src/commands/quoteCommand.ts
- tests/githubAPI.test.ts
That has been broken for a while, the reason comes down to Discord interaction restrictions.
Also a small fix to include quoted username in created PRs, which I find more transparent.
Fixes #356
> Fix the quote command

- src/index.ts
This pull request reverts the debug logging introduced in #534 (hopefully for the last time)
It also updates the call to `Message#fetch` to assign the result of the call to the `message` variable. The documentation doesn't state if `fetch` mutates `this#embeds`, maybe this will make reliability issues go away forever.
> Index: Revert debug logging and maybe fix message fetching

- package.json
There have been zero breaking changes since node 16 that affects us,
so, allow maintainers to use the latest LTS in development and let the
`CI` workflow be a safeguard for those rare instances where somebody
might accidentally use a newer unsupported feature (most of which would
be handled by the typescript transpiler anyways).
> Meta: Allow usage of node version from 16 up to 19

- package.json
- src/apis/githubAPI.ts
- src/commands/commitStatsCommand.ts
- yarn.lock
This commit also includes a quick in-memory repos cache to get rid of one unnecessary API call.
> CommitStatsCommand: Fix an edge-case that could cause inaccurate stats

- src/commands/manCommand.ts
This regressed in 4b088e8 due to changing the embed's main URL from the GitHub one to the `man.serenity.org` one.
The solution was to instead use the GitHub link we have in the embed's description.
> ManCommand: Fix min/max actions

- src/commands/githubCommand.ts
This pull requests updates the mappings for `/github` and friends to not default to the archived ladybird repository.
> GithubCommand: Update channel / category mappings to match ladybird monorepo merge

- package.json
- src/commands/githubCommand.ts
Many people have been using this format for a while now, and even more people like it. As we have already discussed making this a bot command, I let myself be yakbaited into this PR.
The /prlist (or /reviewlist) command creates a @timschumi-style list of PRs, where the PRs are given with their numbers and arbitrary separators. The commands also support the repository option like the regular /pull command.
> Commands: Add a command for creating short PR lists for review

- src/commandHandler.ts
- src/util/embedFromIssueOrPull.ts
- tsconfig.json
1. caef430c7f21d8d94c0efb292a04c48477eea3cb updates the lib version from `es2020` to `esnext` which means that it now matches the rest of the environment, it also means that we don't need that `@ts-expect-error` comment anymore.
2. 80a54bbbac345b8e51b3013df97d5586ddce5085 fixes the `handler.call` callback inside of the `commandHandler` to account for both **`deferred`** and **`replied`** interactions and use the correct `editReply`. Before this a fix we got no proper error output outside of the private (ssh?) terminal which isn't helpful for contributors like me who don't have access to it; so I fixed it.
:^)
> Meta+Commands: Fix one minor and one major issue

- src/commands/index.ts
- src/commands/testCommand.ts
First factor out the common logic from the test262 command file, and move it into utils. Then we can build the testwasm command on top of that as they report results in the same format.
Fixes #844
> Commands: Add testwasm command to print out LibWasm's spec test results 

- src/mastodon.ts
This pull request implements matching all discord emojis in the message and replacing their occurances with a mastodon compatible format.
previously (example from https://serenityos.social/@community/110118247330612172)
```
awesomekling announces:
Going live with <:ladyball:843431401013510165> Office Hours shortly
```
now
```
awesomekling announces:
Going live with :ladyball: Office Hours shortly
```
> Mastodon: Convert discord emoji format to be mastodon compatible

- yarn.lock
Reverts SerenityOS/discord-bot#956
This appears to have caused a regression.
> Revert "Dependencies: Bump @discordjs/builders from 1.6.1 to 1.6.3"

- package.json
We're setting "include" and "exclude" in our tsconfig, but ts-node will only load them if "--files" is passed to it.
This fixes up the "start:dev" command.
> Meta: Specify "--files" when running ts-node

- src/commands/quoteCommand.ts
With these patches, `/quote` seems to work again (on a testing repo of mine, [link](https://github.com/CommandMC/BuggieBot_Test/pull/1)).
I don't know the cause of #533 yet (an issue in the create-pull-request plugin repo points to missing authentication, [link](https://github.com/gr2m/octokit-plugin-create-pull-request/issues/20#issuecomment-532261923)). Could someone with access to the public bot confirm that our issue is still valid?
> QuoteCommand: Getting it working again
